AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Function used to extract data from zendesk

Resources:
  zendeskChatFunction:
    Type: 'AWS::Serverless::Function' # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/raw/function_api_stock
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 600
      Description: A Lambda function created to get data from api.
      Environment:
        Variables:
          ZENDESK_API: zendesk_chats_api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess

  zendeskUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/raw/function_gsheet
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 600
      Description: A Lambda function created to get users data from zendesk.
      Environment:
        Variables:
          ZENDESK_API: zendesk_users_api
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess